config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - menu_ui
third_party_settings:
  lightning_workflow:
    enabled: true
    workflow: editorial
  menu_ui:
    available_menus:
      - main
    parent: 'main:'
  type_style:
    color: '#039BE5'
    icon: book
name: Article
type: article
description: 'Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.'
help: ''
new_revision: false
preview_mode: 0
display_submitted: true
