---
language: php

php: 7.1

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$TMPDIR/phpstan/cache"

env:
  global:
    - ORCA_SUT_NAME=drupal/lightning_core
    - ORCA_SUT_BRANCH=8.x-3.x
    - ORCA_VERSION=v1.0.0-alpha11

matrix:
  fast_finish: true
  include:
    # Standard ORCA jobs.
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Previous minor version of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    # Custom job.
    - { name: "Upgrade test", env: DB_FIXTURE=2.0.0 }

before_install:
  - git clone --branch ${ORCA_VERSION} --depth 1 https://github.com/acquia/orca.git ../orca
  - ../orca/bin/travis/before_install.sh

install:
  - ../orca/bin/travis/install.sh
  - ./tests/travis/install.sh

before_script: ./tests/travis/before_script.sh

script:
  - ../orca/bin/travis/script.sh
  - ./tests/travis/script.sh

after_failure: ../orca/bin/travis/after_failure.sh
