dependencies:
  config:
    - media.type.acquia_dam_asset
settings:
  handler_settings:
    target_bundles:
      acquia_dam_asset: acquia_dam_asset
      image: image
    auto_create: false
    auto_create_bundle: acquia_dam_asset
