version: 1.3.0
services:
  - php:
    version: 7.1

events:
  build:
    steps:
      - build-something:
          script:
            - 'echo "Welcome to Pipelines!"'
  post-deploy:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
