display:
  default:
    display_options:
      filters:
        langcode:
            id: langcode
            table: node_field_data
            field: langcode
            relationship: none
            group_type: group
            admin_label: ''
            operator: in
            value:
              '***LANGUAGE_site_default***': '***LANGUAGE_site_default***'
              en: en
              fr: fr
              es: es
            group: 1
            exposed: true
            expose:
              operator_id: langcode_op
              label: Language
              description: ''
              use_operator: false
              operator: langcode_op
              identifier: langcode
              required: false
              remember: true
              multiple: false
              remember_roles:
                authenticated: authenticated
                anonymous: '0'
                administrator: '0'
                creator: '0'
                marketer: '0'
                reviewer: '0'
              reduce: false
            is_grouped: false
            group_info:
              label: ''
              description: ''
              identifier: ''
              optional: true
              widget: select
              multiple: false
              remember: false
              default_group: All
              default_group_multiple: {  }
              group_items: {  }
            plugin_id: language
            entity_type: node
            entity_field: langcode