language: php
dist: trusty

sudo: false

php:
  - 7.1

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  - echo 'sendmail_path="$(which true)"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Travis automatically CDs into mobomo/media_webdam
  - cd ../../
  - git clone https://github.com/mobomo/media_acquiadam_dev
  - cd media_acquiadam_dev

install:
  - make dependencies
  - rm -r ./modules/contrib/media_acquiadam/*
  - mv $TRAVIS_BUILD_DIR/* ./modules/contrib/media_acquiadam/
  #- make travis-install-site

script:
  - make test-unit
  #- make travis-test-browser

after_script:
  - make report-coverage

notifications:
  slack: mobomo:IUUkblgpWtwuJjnYcBo3a2nN
  email: false
