---
language: php
dist: trusty

php: 7.1

addons:
  ssh_known_hosts:
    - svn-29892.prod.hosting.acquia.com
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

# Execution time is drastically reduced by splitting the build into multiple
# concurrent jobs.
matrix:
  include:
    - name: "Static code analysis"
      env: ORCA_FIXTURE=none
    - name: "Isolated test w/ recommended package versions"
      env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=stable DRUPAL=8.6 DEPLOY=TRUE
    - name: "Integrated test w/ recommended package versions"
      env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=stable
    - name: "Isolated test w/ dev package versions"
      env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=dev
    # Disabled for now because it takes so long to run and isn't needed.
    - name: "Integrated test w/ dev package versions"
      env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=dev
  allow_failures:
    # Temporarily allow standard/stable to fail pending resolution of a Twig
    # problem affecting Lightning API tests.
    - env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=stable
    - env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=dev
    - env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=dev

install:
  - git clone --branch v1.0.0-alpha4 --depth 1 git@github.com:acquia/orca.git ../orca
  - "../orca/bin/travis/install 8.x-1.x"

script: "../orca/bin/travis/script drupal/acquia_contenthub"

deploy:
  - provider: script
    script: ./tests/deploy.sh
    skip_cleanup: true
    on:
      condition: $DEPLOY = TRUE
      all_branches: true
