ip_anon.settings:
  type: config_object
  label: IP Anonymize settings
  mapping:
    policy:
      type: integer
      label: Retention policy
    period_sessions:
      type: integer
      label: Sessions table retention period
    period_comment_field_data:
      type: integer
      label: Comment field data table retention period
    period_watchdog:
      type: integer
      label: Watchdog table retention period
    period_commerce_order:
      type: integer
      label: Commerce order table retention period
    period_login_history:
      type: integer
      label: Login history table retention period
    period_uc_orders:
      type: integer
      label: Ubercart orders table retention period
    period_votingapi_vote:
      type: integer
      label: Voting API vote table retention period
    period_webform_submission:
      type: integer
      label: Webform submission table retention period
    period_yamlform_submission:
      type: integer
      label: YAML form submission table retention period
