field.formatter.settings.assembly_instructions:
  type: mapping
  label: 'Assembly instructions formatter settings'
  mapping:
    view_mode:
      type: string
      label: 'View mode'
    link:
      type: boolean
      label: 'Show links'

field.formatter.settings.comment_average_rating_and_anchor:
  type: mapping
  label: 'Average rating from comments formatter settings'
  mapping:
    anchor:
      type: boolean
      label: 'Provide anchor'
    type:
      type: string
      label: 'Formatter type'

field.formatter.settings.price_with_lower_previous:
  type: mapping
  label: 'Price with lower previous formatter settings'
  mapping:
    strip_trailing_zeroes:
      type: boolean
      label: 'Strip trailing zeroes after the decimal point'
    display_currency_code:
      type: boolean
      label: 'Display the currency code instead of the currency symbol'
