# Schema for the views plugins of DFS Obio commerce.

views.argument_default.obio_taxonomy_tid:
  type: mapping
  label: 'Taxonomy term ID from URL'
  mapping:
    term_page:
      type: boolean
      label: 'Load default filter from term page'
    from_entity:
      type: boolean
      label: 'Load default filter from any kind of entity'
    limit:
      type: boolean
      label: 'Limit terms by vocabulary'
    vids:
      type: sequence
      label: 'Vocabularies'
      sequence:
        type: string
        label: 'Vocabulary'
    anyall:
      type: string
      label: 'Multiple-value handling'
