config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.media.video.field_media_in_library
    - field.field.media.video.field_media_video_embed_field
    - media.type.video
  module:
    - video_embed_field
id: media.video.default
targetEntityType: media
bundle: video
mode: default
content:
  field_media_video_embed_field:
    type: video_embed_field_video
    weight: 0
    label: hidden
    settings:
      responsive: true
      width: 854
      height: 480
      autoplay: true
    third_party_settings: {  }
    region: content
hidden:
  created: true
  field_media_in_library: true
  name: true
  scheduled_publication: true
  thumbnail: true
  uid: true

