config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.article.body
    - field.field.node.article.field_article_subtitle
    - field.field.node.article.field_image
    - field.field.node.article.field_tags
    - field.field.node.article.panelizer
    - image.style.article_teaser
    - node.type.article
  module:
    - image
    - panelizer
    - text
    - user
third_party_settings:
  panelizer:
    enable: false
    custom: false
    allow: false
    default: default
id: node.article.teaser
targetEntityType: node
bundle: article
mode: teaser
content:
  body:
    type: text_summary_or_trimmed
    weight: 3
    settings:
      trim_length: 200
    third_party_settings: {  }
    label: hidden
    region: content
  field_article_subtitle:
    type: string
    weight: 2
    region: content
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
  field_image:
    type: image
    weight: 0
    settings:
      image_style: article_teaser
      image_link: content
    third_party_settings: {  }
    label: hidden
    region: content
  links:
    weight: 4
    region: content
    settings: {  }
    third_party_settings: {  }
  content_moderation_control:
    weight: 1
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  addtoany: true
  field_tags: true
  langcode: true
  panelizer: true
  scheduled_update: true
