config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.rss
    - field.field.node.article.body
    - field.field.node.article.field_article_subtitle
    - field.field.node.article.field_image
    - field.field.node.article.field_tags
    - field.field.node.article.panelizer
    - node.type.article
  module:
    - panelizer
    - user
third_party_settings:
  panelizer:
    enable: false
    custom: false
    allow: false
    default: default
id: node.article.rss
targetEntityType: node
bundle: article
mode: rss
content:
  links:
    weight: 100
    region: content
    settings: {  }
    third_party_settings: {  }
  content_moderation_control:
    weight: -20
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  addtoany: true
  body: true
  field_article_subtitle: true
  field_image: true
  field_tags: true
  langcode: true
  panelizer: true
  scheduled_update: true
