config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - entity_browser.browser.image_browser
    - field.field.node.article.body
    - field.field.node.article.field_article_subtitle
    - field.field.node.article.field_image
    - field.field.node.article.field_tags
    - field.field.node.article.panelizer
    - node.type.article
  module:
    - entity_browser
    - path
    - text
    - content_moderation
id: node.article.default
targetEntityType: node
bundle: article
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: 2
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
    third_party_settings: {  }
    region: content
  created:
    type: datetime_timestamp
    weight: 6
    settings: {  }
    third_party_settings: {  }
    region: content
  fake_moderation_state:
    weight: 50
    region: content
    settings: {  }
    third_party_settings: {  }
  field_article_subtitle:
    weight: 1
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  field_image:
    type: entity_browser_file
    weight: 1
    settings:
      entity_browser: image_browser
      field_widget_edit: true
      field_widget_remove: true
      view_mode: default
      preview_image_style: thumbnail
      open: true
      selection_mode: selection_append
    region: content
    third_party_settings: {  }
  field_tags:
    type: entity_reference_autocomplete_tags
    weight: 4
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  langcode:
    type: language_select
    weight: 3
    settings:
      include_locked: true
    third_party_settings: {  }
    region: content
  path:
    type: path
    weight: 11
    settings: {  }
    third_party_settings: {  }
    region: content
  promote:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 8
    third_party_settings: {  }
    region: content
  status:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 120
    region: content
    third_party_settings: {  }
  sticky:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 9
    third_party_settings: {  }
    region: content
  title:
    type: string_textfield
    weight: 0
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  translation:
    weight: 7
    region: content
    settings: {  }
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 5
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
hidden:
  panelizer: true
  scheduled_update: true
