hidden:
  created: true
  field_acquiadam_asset_captured: true
  field_acquiadam_asset_colorspace: true
  field_acquiadam_asset_descrip: true
  field_acquiadam_asset_file: true
  field_acquiadam_asset_filename: true
  field_acquiadam_asset_filesize: true
  field_acquiadam_asset_filetype: true
  field_acquiadam_asset_folder_id: true
  field_acquiadam_asset_height: true
  field_acquiadam_asset_id: true
  field_acquiadam_asset_type_id: true
  field_acquiadam_asset_version: true
  field_acquiadam_asset_width: true
  field_media_in_library: true
  langcode: true
  name: true
  uid: true
