dependencies:
  module:
    - media_acquiadam
widgets:
  5533b261-83be-4c31-a650-e2ff32cfa3de:
    settings:
      media_type: acquia_dam_asset
      submit_text: 'Select assets'
    uuid: 5533b261-83be-4c31-a650-e2ff32cfa3de
    weight: 4
    label: 'Acquia DAM'
    id: acquiadam
