field_map:
  description: field_acquiadam_asset_descrip
  file: field_acquiadam_asset_file
  type_id: field_acquiadam_asset_type_id
  filename: field_acquiadam_asset_filename
  filesize: field_acquiadam_asset_filesize
  width: field_acquiadam_asset_width
  height: field_acquiadam_asset_height
  filetype: field_acquiadam_asset_filetype
  colorspace: field_acquiadam_asset_colorspace
  version: field_acquiadam_asset_version
  datecreated: created
  datemodified: changed
  datecaptured: field_acquiadam_asset_captured
  folderID: field_acquiadam_asset_folder_id
  status: status
