config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: hero_image
label: 'Hero large (1920x600)'
effects:
  741ab00c-9270-4fc7-ba74-dcefce0e3c12:
    uuid: 741ab00c-9270-4fc7-ba74-dcefce0e3c12
    id: focal_point_scale_and_crop
    weight: 2
    data:
      width: 1920
      height: 600
      crop_type: focal_point
