dependencies:
  config:
    - field.field.node.collection.field_collection_product
content:
  field_collection_product:
    type: entity_reference_autocomplete
    weight: 14
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
